name: 'Frontend - quality check'

on:
  # workflow_dispatch
  pull_request:
    # branches: [main]
    # paths: [frontend/]

defaults:
  run:
    working-directory: frontend

jobs:
  qualtiy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
